[[servers]]
host = "127.0.0.1"
port = 389
use_ssl = false
start_tls = false
ssl_skip_verify = false
bind_dn = "cn=admin,dc=YOURDOMAIN,dc=com"
bind_password = 'xxxxxxxxxxx'
search_filter = "(cn=%s)"
search_base_dns = ["dc=YOURDOMAIN,dc=com"]

[servers.attributes]
name = "givenName"
surname = "sn"
username = "cn"
member_of = "memberOf"
email =  "email"

[[servers.group_mappings]]
group_dn = "cn=administrators,dc=YOURDOMAIN,dc=com"
org_role = "Admin"

[[servers.group_mappings]]
group_dn = "cn=administrators,dc=YOURDOMAIN,dc=com"
org_role = "Editor"

[[servers.group_mappings]]
group_dn = "cn=users,dc=YOURDOMAIN,dc=com"
org_role = "Viewer"

